name: Feed to social media
on:
  workflow_dispatch:

jobs:
  Feed2SocialMedia:
    runs-on: ubuntu-latest
    steps:
      - name: Feed to social media
        uses: lwojcik/github-action-feed-to-social-media@v2
        with:
          feedUrl: 'https://veloroute.hamburg/updates.atom'
          newestItemStrategy: 'latestDate'
          postFormat: "{title}\n{link}"
          # Mastodon settings
          # mastodonEnable: true
          # mastodonPostFormat: "New post: {title}\n\n{link}"
          # mastodonInstance: 'https://mas.to'
          # mastodonAccessToken: 'MASTODON_ACCESS_TOKEN'
          # mastodonPostVisibility: 'unlisted'
          # Mastodon metadata settings
          # mastodonMetadataEnable: true
          # mastodonMetadataInstance: 'https://mas.to'
          # mastodonMetadataAccessToken: 'MASTODON_METADATA_ACCESS_TOKEN'
          # mastodonMetadataFieldIndex: 0
          # Twitter settings
          # twitterEnable: true
          # twitterPostFormat: "New post: {title}\n\n{link}"
          # twitterApiKey: 'TWITTER_API_KEY'
          # twitterApiKeySecret: 'TWITTER_API_SECRET'
          # twitterAccessToken: 'TWITTER_ACCESS_TOKEN'
          # twitterAccessTokenSecret: 'TWITTER_ACCESS_TOKEN_SECRET'
          # Discord settings
          # discordEnable: true
          # discordPostFormat: "New post: {title}\n\n{link}"
          # discordWebhookUrl: 'DISCORD_WEBHOOK_URL'
          # Slack settings
          # slackEnable: true
          # slackPostFormat: "New post: {title}\n\n{link}"
          # slackWebhookUrl: 'DISCORD_WEBHOOK_URL'
          # Bluesky settings
          blueskyEnable: true
          # blueskyPostFormat: "New post: {title}\n\n{link}"
          blueskyHandle: 'VelorouteHH'
          blueskyAppPassword: ${{ secrets.BLUESKYAPPPASSWORD }}
          blueskyOwnerHandle: 'VelorouteHH'
          blueskyOwnerContact:  ${{ secrets.BLUESKYOWNERCONTACT }}
